include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - sort_pub_dependencies
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
